try to build akmods without scriptlets

diff --git a/recipes/recipe.yml b/recipes/recipe.yml
--- a/recipes/recipe.yml
+++ b/recipes/recipe.yml
@@ -18,18 +18,24 @@ modules:
         # 2. Install kernel headers and build tools needed for the driver
         RUN rpm-ostree install kernel-devel kernel-headers akmods
         
-        # 3. Install the DisplayLink components.
-        # Note: rpm-ostree doesn't support --setopt or --assume-yes (those are DNF options).
-        # If akmod-evdi gets pulled in as a weak dependency and causes issues,
-        # we'll build evdi manually in the next step anyway.
-        RUN rpm-ostree install \
-            libevdi \
-            displaylink
+        # 3. Install libevdi first (this should not pull in akmod-evdi)
+        RUN rpm-ostree install libevdi
         
-        # 4. Manually trigger the akmod build for evdi using the correct parameters
-        # for a containerized build environment. This ensures evdi is built correctly
-        # even if akmod-evdi was installed or if it needs to be built from source.
-        RUN akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi
+        # 4. Install displaylink. akmod-evdi will be pulled in as a dependency.
+        # The akmod-evdi package's post-install scriptlet will fail because it tries
+        # to build as root. We'll work around this by installing akmod-evdi manually
+        # without running its scriptlets, then installing displaylink.
+        RUN dnf download akmod-evdi -y && \
+            rpm -Uvh --noscripts akmod-evdi*.rpm && \
+            rm -f akmod-evdi*.rpm || true
+        
+        # 5. Now install displaylink (akmod-evdi is already installed, so it won't try to build)
+        RUN rpm-ostree install displaylink
+        
+        # 6. Manually trigger the akmod build for evdi using the akmods user.
+        # This ensures evdi is built correctly since we installed akmod-evdi without scriptlets.
+        RUN su -s /bin/bash akmods -c "akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi" || \
+            akmods --force --kernels $(rpm -q kernel-devel --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' | tail -n 1) --akmod evdi
 
   # Finally, our tuning script to enable the service and set config
   - type: script
